[platformio]
default_envs = sparkfun_promicro16

[env:sparkfun_promicro16]
platform    = atmelavr
board       = sparkfun_promicro16
framework   = arduino
build_flags = -DBOARD_PROMICRO
lib_deps    =
    NicoHood/HID-Project @ ^2.6.1

[env:uiapduino]
platform    = atmelavr
board       = uiapduino
framework   = arduino
build_flags = -DBOARD_UIAPDUINO
lib_deps    =
    NicoHood/HID-Project @ ^2.6.1

[env:native]
platform       = native
test_framework = unity
build_flags    = -std=c++14
